#!/usr/bin/python3

from berry_mill import ImageMill
from typing import Any
import sys

if __name__ == "__main__":
    mill:Any = None
    try:
        mill = ImageMill()
    except Exception as exc:
        mill.cleanup()
        print("General error:", exc)
        sys.exit(1)

    try:
        mill.run()
    except Exception as exc:
        mill.cleanup()
        print("Error:", exc)
        if mill.args.debug:
            raise
    except SystemExit as e:
        mill.cleanup()
        raise e