#!/usr/bin/python3

from berry_mill import ImageMill

if __name__ == "__main__":
    mill = ImageMill()

    try:
        mill.run()
    except Exception as exc:
        print("Error:", exc)
        if mill.args.debug:
            raise
