name: Check PEP8 syntax errors
run-name: Check PEP8 formatting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set the importance environment variable
        run: |
          echo "GITHUB_ACTIONS_IMPORTANCE=true" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Display curent dir
        run : ls -la $GITHUB_WORKSPACE

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install mtools e2fsprogs cryptsetup-bin dosfstools fdisk libparted-dev fakeroot

      - name: Install pip deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: PEP8 syntax errors or undefined names
        run: |
          flake8 . --count --select=E9,F63,F7 --show-source --statistics
