name: pytest-workflow
run-name: Execute Berrymill unit tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set the importance environment variable
        run: |
          echo "GITHUB_ACTIONS_IMPORTANCE=true" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Display curent dir
        run : ls -la $GITHUB_WORKSPACE

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install mtools e2fsprogs cryptsetup-bin dosfstools fdisk libparted-dev fakeroot

      - name: Install pip deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest --cov=berry_mill test/

        if: ${{ env.GITHUB_ACTIONS_IMPORTANCE == 'true' }}
